.TH PARTITIONMANAGER "1" "December 2016" "partitionmanager" "User Commands"
.SH NAME
partitionmanager \- Partition manager for KDE
.SH SYNOPSIS
.B partitionmanager
[\fI\,options\/\fR] [\fI\,device\/\fR...]
.SH DESCRIPTION
Manage your disks, partitions and file systems
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Displays this help.
.TP
\fB\-v\fR, \fB\-\-version\fR
Displays version information.
.TP
\fB\-\-author\fR
Show author information.
.TP
\fB\-\-license\fR
Show license information.
.TP
\fB\-\-desktopfile\fR <file name>
The base file name of the desktop entry for this
application.
.TP
\fB\-\-dontsu\fR
Do not try to gain super user privileges
.TP
\fB\-\-advconfig\fR
Show advanced tab in configuration dialog
.SS "Arguments:"
.TP
device
Device(s) to manage

